name: wallet_api_flutter
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.4+1
  bloc: ^6.1.1  
  built_value: ^7.1.0
  built_collection: ^4.3.2
  wallet_sdk_flutter:
    git: https://github.com/Sugar-Foundation/wallet_sdk_flutter
  network_flutter:
    git: https://github.com/Sugar-Foundation/network_flutter
  utils_flutter:
    git: https://github.com/Sugar-Foundation/utils_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.8.2
  built_value_generator: ^7.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
